trigger:
  - "*"
pool:
  name: myAgents
variables:
  buildConfiguration: "Release"
  wwwroot: "Tailspin.SpaceGame.Web/wwwroot"
steps:
  - task: Npm@1
    displayName: "Run npm install"
    inputs:
      verbose: false
  - script: "./node_modules/.bin/node-sass $(wwwroot) --output $(wwwroot)"
    displayName: "Compile Sass assets"

  - task: gulp@1
    displayName: "Run gulp tasks"

  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: "Write build info"
    workingDirectory: $(wwwroot)

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - template: templates/build.yml
    parameters:
      buildConfiguration: "Debug"

  - template: templates/build.yml
    parameters:
      buildConfiguration: "Release"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    condition: succeeded()
